<?php include __DIR__ . '/header.phtml'; ?>

<main>
    <div class="container d-flex flex-column align-items-center my-5">
    <form class="w-100 d-flex justify-content-center">
        
        <fieldset class="border border-black p-4" 
                  style="max-width: 700px; width:100%">
            
            <legend class="px-2">Connexion</legend>

            <div class="mb-3 text-start">
                <label for="pseudo" class="form-label">Email</label>
                <input id="pseudo" name="pseudo" type="text" 
                       class="form-control" required>
            </div>

            <div class="mb-4 text-start">
                <label for="password" class="form-label">Mot de passe *</label>
                <input id="password" name="password" type="password" 
                       class="form-control" required>
            </div>

            <button id="submit" type="submit" 
                    class="btn btn-dark w-100 py-2">
                Se connecter
            </button>

            <div class="auth-messages mt-3" aria-live="polite"></div>

            <p class="mt-3 text-center">
                Pas encore inscrit ? 
                <a href="inscription.php">S'inscrire</a>
            </p>
        </fieldset>

    </form>
</div>                       
</main>

<?php include __DIR__ . '/footer.phtml'; ?>
