        <footer>
            <p>Pierre | EcoRide | <a href="https://entreprendre.service-public.gouv.fr/vosdroits/F33527">Mentions Légale</a> | <a href="#">Haut de page</a></p>
        </footer>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>   

    </body>
</html>
