<?php include __DIR__ . '/header.phtml'; ?>

    <main>
        <form class="w-100 d-flex justify-content-center my-5">
    <fieldset class="border border-black p-4" style="max-width: 700px; width:100%">
        <legend class="px-2">Inscription</legend>

        <div class="mb-3 text-start">
            <label for="nom" class="form-label">Nom *</label>
            <input id="nom" name="nom" class="form-control" required>
        </div>

        <div class="mb-3 text-start">
            <label for="prenom" class="form-label">Prénom *</label>
            <input id="prenom" name="prenom" class="form-control" required>
        </div>

        <div class="mb-3 text-start">
            <label for="pseudo" class="form-label">Pseudo *</label>
            <input id="pseudo" name="pseudo" class="form-control" required>
        </div>

        <div class="mb-3 text-start">
            <label for="email" class="form-label">Email *</label>
            <input id="email" name="email" type="email" class="form-control" required>
        </div>

        <div class="mb-3 text-start">
            <label for="password" class="form-label">Mot de passe *</label>
            <input id="password" name="password" type="password" class="form-control" required>
        </div>

        <div class="mb-4 text-start">
            <label for="confirm-password" class="form-label">Confirmer *</label>
            <input id="confirm-password" name="confirm-password" type="password" class="form-control" required>
        </div>

        <div class="form-check mb-4 text-start">
            <input class="form-check-input" type="checkbox" id="chauffeur" name="chauffeur">
            <label class="form-check-label" for="chauffeur">
                Je suis chauffeur
            </label>
        </div>

        <button type="submit" class="btn btn-dark w-100 py-2">
            S'inscrire
        </button>

        <p class="mt-3 text-center">
            Déjà inscrit ? <a href="connexion.php">Se connecter</a>
        </p>
    </fieldset>
        </form>
    </main>
    
<?php include __DIR__ . '/footer.phtml'; ?>